@host=http://localhost:8080

### execute dmn ###
#POST {{host}}/assetCalculations http/1.1
POST {{host}}/assetCalculations/getTotalAnticipatedRealEstateSalesProceedsAmount http/1.1
Content-Type: application/json

{
    "context": {
        "submittedDate": "2020-07-25"
    },
    "realEstateOwnedProperties": [
        {
            "identifier": "REO_1",
            "dispositionStatusType": "PendingSale",
            "lienUPBAmount": 50000
        },
        {
            "identifier": "REO_2",
            "dispositionStatusType": "PendingSale",
            "lienUPBAmount": 50000,
            "propertyEstimatedValueAmount": 100000
        },
        {
            "identifier": "REO_3",
            "dispositionStatusType": "Sold",
            "lienUPBAmount": 50000,
            "propertyValuationAmount": 80000
        }
    ],
    "relationships": [
        {
            "from": "Borrower_A",
            "to": "REO_1",
            "arcRole": "ASSET_IsAssociatedWith_ROLE"
        },
        {
            "from": "Borrower_B",
            "to": "REO_2",
            "arcRole": "ASSET_IsAssociatedWith_ROLE"
        }
    ]
}


### execute dmn with nulls ###
POST {{host}}/assetCalculations http/1.1
Content-Type: application/json

{
    "context": {
        "submittedDate": "2020-07-25"
    },
    "realEstateOwnedProperties": [
        {
            "identifier": "REO_1",
//            "dispositionStatusType": "PendingSale",
            "lienUPBAmount": 50000
        },
        {
            "identifier": "REO_2",
//            "dispositionStatusType": "PendingSale",
            "lienUPBAmount": 50000,
            "propertyEstimatedValueAmount": 100000
        },
        {
            "identifier": "REO_3",
//            "dispositionStatusType": "Sold",
            "lienUPBAmount": 50000,
            "propertyValuationAmount": 80000
        }
    ],
    "relationships": [
        {
            "from": "Borrower_A",
            "to": "REO_1",
            "arcRole": "ASSET_IsAssociatedWith_ROLE"
        },
        {
            "from": "Borrower_B",
            "to": "REO_2",
            "arcRole": "ASSET_IsAssociatedWith_ROLE"
        }
    ]
}
